routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/view/category/{id}','frontController@singlePage')->name('category.front')->middleware('auth');

Route::get('borrow/book/{id}','frontController@borrow')->name('borrow')->middleware('auth');
Route::get('list/user/borrow','frontController@listBorrowBook')->name('my_borrow_book')->middleware('auth');
Route::get('/cancel/borrow/{id}','frontController@cancel')->name('borrow.cancel')->middleware('auth');

Route::get('/about','HomeController@about')->name('about');
Route::get('/contact','HomeController@contact')->name('contact');


Route::get('/live/search/{str}','SearchController@search');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('category', 'categoriesController');
    Route::resource('author', 'AuthorContoller');
    Route::get('/admin', 'HomeController@admin')->name('admin');

    Route::resource('/users', 'UsersController');
    Route::get('/users/admin/{id}', 'UsersController@makeAdmin')->name('users.admin');
    Route::get('/users/admin/user/{id}', 'UsersController@makeNotAdmin')->name('users.user');
    Route::resource('/profiles/change', 'profileController');

    Route::get('/request','BorrowRequestController@borrow')->name('book.request');
    Route::get('/accept/{id}','BorrowRequestController@accept')->name('borrow.accept');
    Route::get('/admin/cancel/{id}','BorrowRequestController@admin_cancel')->name('admin.cancel');



    Route::resource('books', 'BookController');
    Route::get('/trashed', 'BookController@trashed')->name('books.trashed');
    Route::delete('/kill/{id}', 'BookController@kill')->name('books.kill');
    Route::get('/restore/{id}', 'BookController@restore')->name('books.restore');



});

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Book extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];

    protected $guarded = [];

    /**
     * @param array $attributes
     */
    public function setNameAttribute($value)
    {
        $this->attributes['name'] = strtolower($value);
    }


    public function category()
    {
        return $this->belongsTo(\APP\Category::class);
    }


    public function author()
    {
        return $this->belongsTo(Author::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class)->withPivot('user_id','book_id');
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Author;
use App\Book;
use App\Category;
use Illuminate\Http\Request;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $all_books = Book::all();
        return view('admin.books.index')->with('all_posts',$all_books);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::all();

        if ($category->count() == 0) {
            session()->flash('info', 'you must have one category');
            return redirect()->back();
        }
        $author = Author::all();

        if ($author->count() == 0) {
            session()->flash('info', 'you must have one Author');
            return redirect()->back();
        }


        return view('admin.books.create', compact('category'))->with('authors', Author::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'title' => 'required',
            'ISN'=>'required|unique:books',
            'featured' => 'required|image',
            'number' => 'required',
            'category_id' => 'required',
            'author_id' => 'required'
        ],[],[
            'tags'=>'author'
        ]);

        $featured = $request->featured;
        $newFeatured = time() . $featured->getClientOriginalName();

        $featured->move('uploads', $newFeatured);

        $post = Book::create([
            'name' => $request->title,
            'ISN'=>$request->ISN,
            'book_cover' =>$newFeatured,
            'number' => $request->number,
            'category_id' => $request->category_id,
            'author_id'=>$request->author_id,
        ]);

        session()->flash('success', 'Book created successful');

        return redirect()->route('books.index');


    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::find($id);
        $category = Category::all();
        return view('admin.books.edit', ['book' => $book, 'category' => $category])->with('authors', Author::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'ISN'=>'required',
            'number' => 'required',
            'category_id' => 'required',
            'author_id' => 'required'
        ],[],[
            'tags'=>'author'

        ]);

        $post = Book::find($id);

        if ($request->hasFile('featured')) {
            $featured = $request->featured;
            $feturead_new_name = time() . $featured->getClientOriginalName();
            $featured->move('uploads', $feturead_new_name);
            $post->book_cover = $feturead_new_name;
        }

        $post->update([
            'name' => $request->title,
            'ISN'=>$request->ISN,
            'number' => $request->number,
            'category_id' => $request->category_id,
            'author_id'=>$request->author_id,
        ]);

        session()->flash('success', 'Book update success');
        return redirect()->route('books.index');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Book::find($id)->delete();
        session()->flash('success', 'Book trashed successfuly');
        return back();
    }

    public function trashed()
    {
        $trashed = Book::onlyTrashed()->get();

        return view('admin.books.trashed', ['trahsed' => $trashed]);

    }

    public function kill($id)
    {
        $trashed = Book::withTrashed()->where('id', $id)->first();
        $trashed->forceDelete();

        session()->flash('success', 'Books Deleted successfully');
        return back();

    }

    public function restore($id)
    {
        $restore = Book::withTrashed()->where('id', $id)->first();

        $restore->restore();
        session()->flash('success', 'Book restored successfully');

        return redirect()->route('books.trashed');
    }


}

resources/views/admin/books/create.blade.php
@extends('layouts.adminLayout')
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card">
        <div class="card-header">
            Add New Book
        </div>
        <div class="card-header">
            <form action="{{route('books.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="title">Name</label>
                    <input type="text" name="title" class="form-control" value="{{old('title')}}">

                </div>
                <div class="form-group">
                    <label for="ISN">ISN</label>
                    <input type="number" value="{{old('ISN')}}" name="ISN" class="form-control">
                </div>

                <div class="form-group">
                    <label for="featured">Book cover image</label>
                    <input type="file" name="featured" class="form-control" value="{{old('featured')}}">

                </div>

                <div class="form-group">
                    <label for="author_id">Select Author</label>
                    <select name="author_id" class="form-control">
                        @foreach($authors as $auth)
                            <option value="{{$auth->id}}">{{$auth->name}}</option>
                        @endforeach

                    </select>

                </div>

                <div class="form-group">
                    <label for="category">Select Category</label>
                    <select name="category_id" class="form-control">
                        @foreach($category as $cat)
                            <option value="{{$cat->id}}">{{$cat->name}}</option>
                        @endforeach

                    </select>

                </div>

                <div class="form-group">
                    <label for="number">Select Number of copies</label>
                    <input type="number" value="{{old('number')}}" name="number" class="form-control">
                </div>



                <div class="form-group">
                    <div class="text-center">
                        <button class="btn btn-success" type="submit">Store Book</button>
                    </div>
                </div>


            </form>
        </div>
    </div>

@endsection

resources/views/admin/books/edit.blade.php
@extends('layouts.adminLayout')
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card">
        <div class="card-header">
            Add New Book
        </div>
        <div class="card-header">
            <form action="{{route('books.update',['id'=>$book->id])}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="form-group">
                    <label for="title">Name</label>
                    <input type="text" name="title" class="form-control" value="{{$book->name}}">

                </div>

                <div class="form-group">
                    <label for="ISN">ISN</label>
                    <input type="number" value="{{$book->ISN}}" name="ISN" class="form-control">
                </div>

                <div class="form-group">
                    <label for="featured">Book cover image</label>
                    <input type="file" name="featured" class="form-control">

                </div>


                <div class="form-group">
                    <label for="author_id">Select Author</label>
                    <select name="author_id" class="form-control">
                        @foreach($authors as $auth)
                            <option value="{{$auth->id}}"
                                    @if($book->author_id == $auth->id)
                                    selected
                                    @endif
                            >{{$auth->name}}</option>
                        @endforeach

                    </select>

                </div>

                <div class="form-group">
                    <label for="category">Select Category</label>
                    <select name="category_id" class="form-control">
                        @foreach($category as $cat)
                            <option value="{{$cat->id}}"
                                    @if($book->category_id == $cat->id)
                                    selected
                                    @endif

                            >{{$cat->name}}</option>
                        @endforeach

                    </select>

                </div>

                <div class="form-group">
                    <label for="number">Select Number</label>
                    <input type="number" value="{{$book->number}}" name="number" class="form-control">
                </div>




                <div class="form-group">
                    <div class="text-center">
                        <button class="btn btn-success" type="submit">Store Book</button>
                    </div>
                </div>


            </form>
        </div>
    </div>

@endsection

resources/views/admin/books/index.blade.php
@extends('layouts.adminLayout')
@section('content')


    <div class="card">

        <div class="card-body">
            <table class="table table-hover">
                <tr>
                    <th>cover</th>
                    <th>name</th>
                    <th>available copies</th>
                    <th>Status</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                <tbody>
                @if($all_posts->count() > 0)

                    @foreach($all_posts as $post)
                        <tr>
                            <td><img src="{{asset('uploads/'.$post->book_cover)}}" width="80px" height="80px"></td>
                            <td>{{$post->name}}</td>
                            <td>{{$post->number}}</td>
                            <td>{{$post->status}}</td>
                            <td><a href="{{route('books.edit',['id'=>$post->id])}}" class="btn btn-success">Edit</a></td>
                            <td>
                                <form action="{{route('books.destroy',['id'=>$post->id])}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <input type="submit" value="Delete" class="btn btn-danger">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <th colspan="5" class="text-center">No Books</th>
                    </tr>
                @endif


                </tbody>
            </table>
        </div>
    </div>



@endsection

resources/views/admin/books/trashed.blade.php
@extends('layouts.adminLayout')
@section('content')


    <div class="card">

        <div class="card-body">
            <table class="table table-hover">
                <tr>
                    <th>book cover</th>
                    <th>name</th>
                    <th>Restore</th>
                    <th>Destroy</th>
                </tr>
                <tbody>
                @if($trahsed->count() >0)
                    @foreach($trahsed as $post)
                        <tr>
                            <td><img src="{{asset('uploads/'.$post->book_cover)}}" width="80px" height="80px"></td>
                            <td>{{$post->name}}</td>
                            <td><a href="{{route('books.restore',['id'=>$post->id])}}"
                                   class="btn btn-success">Restore</a></td>
                            <td>
                                <form action="{{route('books.kill',['id'=>$post->id])}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <input type="submit" value="Delete" class="btn btn-danger">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <th colspan="5" class="text-center">No Trashed Books</th>
                    </tr>
                @endif

                </tbody>
            </table>
        </div>
    </div>



@endsection