routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/view/category/{id}','frontController@singlePage')->name('category.front')->middleware('auth');

Route::get('borrow/book/{id}','frontController@borrow')->name('borrow')->middleware('auth');
Route::get('list/user/borrow','frontController@listBorrowBook')->name('my_borrow_book')->middleware('auth');
Route::get('/cancel/borrow/{id}','frontController@cancel')->name('borrow.cancel')->middleware('auth');

Route::get('/about','HomeController@about')->name('about');
Route::get('/contact','HomeController@contact')->name('contact');


Route::get('/live/search/{str}','SearchController@search');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('category', 'categoriesController');
    Route::resource('author', 'AuthorContoller');
    Route::get('/admin', 'HomeController@admin')->name('admin');

    Route::resource('/users', 'UsersController');
    Route::get('/users/admin/{id}', 'UsersController@makeAdmin')->name('users.admin');
    Route::get('/users/admin/user/{id}', 'UsersController@makeNotAdmin')->name('users.user');
    Route::resource('/profiles/change', 'profileController');

    Route::get('/request','BorrowRequestController@borrow')->name('book.request');
    Route::get('/accept/{id}','BorrowRequestController@accept')->name('borrow.accept');
    Route::get('/admin/cancel/{id}','BorrowRequestController@admin_cancel')->name('admin.cancel');



    Route::resource('books', 'BookController');
    Route::get('/trashed', 'BookController@trashed')->name('books.trashed');
    Route::delete('/kill/{id}', 'BookController@kill')->name('books.kill');
    Route::get('/restore/{id}', 'BookController@restore')->name('books.restore');



});

resources/views/layouts/adminLayout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('styles')
</head>
<body>


<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">

            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>


    <div class="container mt-5">
        @if(session()->has('success'))
            <p class="alert alert-success">{{session()->get('success')}}</p>
        @endif

        @if(session()->has('info'))
            <p class="alert alert-danger">{{session()->get('info')}}</p>
        @endif

        <div class="row">
            @if (auth()->check())
                <div class="col-lg-4">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <a href="{{route('admin')}}">Home</a>
                        </li>

                        <li class="list-group-item">
                            <a href="{{route('books.index')}}">All Books</a>
                        </li>

                        <li class="list-group-item">
                            <a href="{{route('books.trashed')}}">All Trashed Books</a>
                        </li>

                        <li class="list-group">
                            <div class="list-group-item">
                                <a href="{{route('books.create')}}">Add New Book</a>
                            </div>
                        </li>

                        <li class="list-group-item">
                            <a href="{{route('category.index')}}">Categories</a>
                        </li>


                        <li class="list-group-item">
                            <a href="{{route('category.create')}}">Create New Category</a>
                        </li>

                        <li class="list-group-item">
                            <a href="{{route('author.index')}}">Authors</a>
                        </li>


                        <li class="list-group-item">
                            <a href="{{route('author.create')}}">Create New Author</a>
                        </li>

                        <li class="list-group-item">
                            <a href="{{route('users.index')}}">Users</a>
                        </li>

                        <li class="list-group-item">
                            <a href="{{route('users.create')}}">Create User</a>
                        </li>

                        <li class="list-group-item">
                            <a href="{{route('change.index')}}">My Profile</a>
                        </li>

                        <li class="list-group-item">
                            <a href="{{route('book.request')}}">Borrow Request</a>
                        </li>


                    </ul>
                    @endif
                </div>
                <div class="col-lg-8">
                    @yield('content')
                </div>
        </div>
    </div>

</div>
@yield('js')

</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/front.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                Smart Library
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">
                    @if(auth()->user())
                        @foreach($category as $cat)
                            <li class="nav-item">
                                <a href="{{route('category.front',['id'=>$cat->id])}}"
                                   class="nav-link">{{$cat->name}}</a>
                            </li>

                        @endforeach
                    @else
                        <li class="nav-item">
                            <a href="{{route('about')}}"
                               class="nav-link">About Us</a>
                        </li>

                        <li class="nav-item">
                            <a href="{{route('contact')}}"
                               class="nav-link">Contact Us</a>
                        </li>

                    @endif


                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">

                    <li class="nav-item p-1 ">
                        <label for="search">Search</label>
                        <input type="text" name="search" placeholder="Search by name" id="search">
                        <div id="livesearch" class="ml-5 align-center text-center" style=" position: absolute; width: 200px ;font-size:24px; " ></div>

                    </li>



                    @if(auth()->user())
                        <li class="nav-item">
                            <a href="{{route('my_borrow_book')}}" class="nav-link btn btn-success">Borrowing Books</a>
                        </li>
                    @else

                    @endif


                <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>

<script>
    window.addEventListener('load', function () {


        var val = document.querySelector('#search');

         document.getElementById("livesearch").innerHTML = "";
         document.getElementById("livesearch").style.border = "0px";

        val.addEventListener('keyup', function () {
            if(!val.value){
                document.getElementById("livesearch").innerHTML = "";
                document.getElementById("livesearch").style.border = "0px";
            }


            if (window.XMLHttpRequest) {
                // code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp = new XMLHttpRequest();
            } else {  // code for IE6, IE5
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    let str_arr = this.responseText.split(',');
                    for(var i = 0; i < str_arr.length; i++){

                        document.getElementById("livesearch").innerHTML = "<p>"+ str_arr[i].slice(1,-2)+"</p>";
                    }

                    document.getElementById("livesearch").style.border = "1px solid #A5ACB2";
                }
            }
            xmlhttp.open("GET", "/live/search/" + val.value.toLowerCase(), true);
            xmlhttp.send();





        });

    });

</script>
</body>
</html>