routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/view/category/{id}','frontController@singlePage')->name('category.front')->middleware('auth');

Route::get('borrow/book/{id}','frontController@borrow')->name('borrow')->middleware('auth');
Route::get('list/user/borrow','frontController@listBorrowBook')->name('my_borrow_book')->middleware('auth');
Route::get('/cancel/borrow/{id}','frontController@cancel')->name('borrow.cancel')->middleware('auth');

Route::get('/about','HomeController@about')->name('about');
Route::get('/contact','HomeController@contact')->name('contact');


Route::get('/live/search/{str}','SearchController@search');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('category', 'categoriesController');
    Route::resource('author', 'AuthorContoller');
    Route::get('/admin', 'HomeController@admin')->name('admin');

    Route::resource('/users', 'UsersController');
    Route::get('/users/admin/{id}', 'UsersController@makeAdmin')->name('users.admin');
    Route::get('/users/admin/user/{id}', 'UsersController@makeNotAdmin')->name('users.user');
    Route::resource('/profiles/change', 'profileController');

    Route::get('/request','BorrowRequestController@borrow')->name('book.request');
    Route::get('/accept/{id}','BorrowRequestController@accept')->name('borrow.accept');
    Route::get('/admin/cancel/{id}','BorrowRequestController@admin_cancel')->name('admin.cancel');



    Route::resource('books', 'BookController');
    Route::get('/trashed', 'BookController@trashed')->name('books.trashed');
    Route::delete('/kill/{id}', 'BookController@kill')->name('books.kill');
    Route::get('/restore/{id}', 'BookController@restore')->name('books.restore');



});

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{

    public function books()
    {
        return $this->hasMany(\App\Book::class);
    }
}

resources/views/admin/authors/create.blade.php
@extends('layouts.adminLayout')
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card">
        <div class="card-header">
            Create New Author
        </div>
        <div class="card-header">
            <form action="{{route('author.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" class="form-control" value="{{old('name')}}">

                </div>
                <div class="form-group">
                    <div class="text-center">
                        <button class="btn btn-success" type="submit">Store Author</button>
                    </div>
                </div>


            </form>
        </div>
    </div>

@endsection

resources/views/admin/authors/edit.blade.php
@extends('layouts.adminLayout')
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card">
        <div class="card-header">
            Edit Category {{$category->name}}
        </div>
        <div class="card-header">
            <form action="{{route('author.update',['id'=>$category->id])}}" method="post">
                @csrf
                @method('PATCH')
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" class="form-control" value="{{$category->name}}">

                </div>
                <div class="form-group">
                    <div class="text-center">
                        <button class="btn btn-success" type="submit">Store Author</button>
                    </div>
                </div>


            </form>
        </div>
    </div>

@endsection

resources/views/admin/authors/index.blade.php
@extends('layouts.adminLayout')
@section('content')


    <div class="card">

        <div class="card-body">
            <table class="table table-hover">
                <tr>
                    <th>Name</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                <tbody>
                @if($categories->count() > 0)
                    @foreach($categories as $category)
                        <tr>
                            <td>{{$category->name}}</td>
                            <td>
                                <a href="{{route('author.edit',['id'=>$category->id])}}" class="btn btn-info">Edit</a>

                            </td>
                            <td>
                                <form action="{{route('author.destroy',['id'=>$category->id])}}" method="post">
                                    <input type="submit" value="Delete" class="btn btn-danger">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </td>
                        </tr>
                    @endforeach

                @else
                    <tr>
                        <th colspan="5" class="text-center">No Authors</th>
                    </tr>
                @endif


                </tbody>
            </table>
        </div>
    </div>



@endsection